[
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "042b157d-9cf6-40a7-a14b-c59490d1c9da",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.553Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:05.441Z",
      "completed_on": "2024-04-18T08:31:05.689Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "3653fe19-b3fa-4474-865e-3d4f24bed574",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:05,442|INFO|STARTED [queue: \"default\", task: \"042b157d-9cf6-40a7-a14b-c59490d1c9da\", job: \"3653fe19-b3fa-4474-865e-3d4f24bed574\"]\n2024-04-18 08:31:05,445|INFO|Loading participants from Kronos\n2024-04-18 08:31:05,685|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:05,687|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:05,690|INFO|FAILURE [queue: \"default\", task: \"042b157d-9cf6-40a7-a14b-c59490d1c9da\", job: \"3653fe19-b3fa-4474-865e-3d4f24bed574\"]\n",
      "event": 1,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "07002d7f-48d5-469c-995d-78a281ac7cb6",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.447Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:00.433Z",
      "completed_on": "2024-04-18T08:31:00.759Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "23f199ad-6c1a-45f3-b6b6-20e929f1e145",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:00,434|INFO|STARTED [queue: \"default\", task: \"07002d7f-48d5-469c-995d-78a281ac7cb6\", job: \"23f199ad-6c1a-45f3-b6b6-20e929f1e145\"]\n2024-04-18 08:31:00,437|INFO|Loading participants from Kronos\n2024-04-18 08:31:00,755|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:00,757|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:00,760|INFO|FAILURE [queue: \"default\", task: \"07002d7f-48d5-469c-995d-78a281ac7cb6\", job: \"23f199ad-6c1a-45f3-b6b6-20e929f1e145\"]\n",
      "event": 3,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "1056498f-39bd-409a-9f1c-d81e179ce5b6",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.538Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:04.815Z",
      "completed_on": "2024-04-18T08:31:05.093Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "673c9dff-0f39-46e7-a61b-8e864a60eed3",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:04,816|INFO|STARTED [queue: \"default\", task: \"1056498f-39bd-409a-9f1c-d81e179ce5b6\", job: \"673c9dff-0f39-46e7-a61b-8e864a60eed3\"]\n2024-04-18 08:31:04,820|INFO|Loading participants from Kronos\n2024-04-18 08:31:05,092|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:05,092|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:05,093|INFO|FAILURE [queue: \"default\", task: \"1056498f-39bd-409a-9f1c-d81e179ce5b6\", job: \"673c9dff-0f39-46e7-a61b-8e864a60eed3\"]\n",
      "event": 16,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "14108fbc-897d-4b08-8e9e-b0733210fbd6",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.495Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:02.782Z",
      "completed_on": "2024-04-18T08:31:03.422Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "7ea2dc5c-27fa-42aa-a36f-bb19c16ff054",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:02,783|INFO|STARTED [queue: \"default\", task: \"14108fbc-897d-4b08-8e9e-b0733210fbd6\", job: \"7ea2dc5c-27fa-42aa-a36f-bb19c16ff054\"]\n2024-04-18 08:31:02,786|INFO|Loading participants from Kronos\n2024-04-18 08:31:03,419|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:03,420|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:03,422|INFO|FAILURE [queue: \"default\", task: \"14108fbc-897d-4b08-8e9e-b0733210fbd6\", job: \"7ea2dc5c-27fa-42aa-a36f-bb19c16ff054\"]\n",
      "event": 5,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "149244e7-d110-4e73-a729-edc294e03f34",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.512Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:03.791Z",
      "completed_on": "2024-04-18T08:31:04.044Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "b6fb80f4-def9-4bd9-88a7-cb24cea987bc",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:03,792|INFO|STARTED [queue: \"default\", task: \"149244e7-d110-4e73-a729-edc294e03f34\", job: \"b6fb80f4-def9-4bd9-88a7-cb24cea987bc\"]\n2024-04-18 08:31:03,796|INFO|Loading participants from Kronos\n2024-04-18 08:31:04,043|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:04,043|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:04,044|INFO|FAILURE [queue: \"default\", task: \"149244e7-d110-4e73-a729-edc294e03f34\", job: \"b6fb80f4-def9-4bd9-88a7-cb24cea987bc\"]\n",
      "event": 13,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "157b9020-09a8-4f32-8996-1b3ee0b26acf",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.478Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:02.016Z",
      "completed_on": "2024-04-18T08:31:02.289Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "2856defb-dc0b-40f9-8d6a-a0749f6321c7",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:02,017|INFO|STARTED [queue: \"default\", task: \"157b9020-09a8-4f32-8996-1b3ee0b26acf\", job: \"2856defb-dc0b-40f9-8d6a-a0749f6321c7\"]\n2024-04-18 08:31:02,021|INFO|Loading participants from Kronos\n2024-04-18 08:31:02,284|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:02,287|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:02,289|INFO|FAILURE [queue: \"default\", task: \"157b9020-09a8-4f32-8996-1b3ee0b26acf\", job: \"2856defb-dc0b-40f9-8d6a-a0749f6321c7\"]\n",
      "event": 2,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "17f3b157-764c-4c8f-9270-a2e18084f7ac",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.400Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:30:58.260Z",
      "completed_on": "2024-04-18T08:30:59.116Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "703dcf5e-8ff6-4e76-b66a-30e02c576299",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:30:58,261|INFO|STARTED [queue: \"default\", task: \"17f3b157-764c-4c8f-9270-a2e18084f7ac\", job: \"703dcf5e-8ff6-4e76-b66a-30e02c576299\"]\n2024-04-18 08:30:58,263|INFO|Loading participants from Kronos\n2024-04-18 08:30:59,114|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:30:59,115|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:30:59,116|INFO|FAILURE [queue: \"default\", task: \"17f3b157-764c-4c8f-9270-a2e18084f7ac\", job: \"703dcf5e-8ff6-4e76-b66a-30e02c576299\"]\n",
      "event": 19,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "2a26f439-b2af-4ad0-8c43-09c7453c069f",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.417Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:30:59.158Z",
      "completed_on": "2024-04-18T08:30:59.531Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "3ceed45c-e11c-4e9b-aa35-2d9cf9cee9c7",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:30:59,159|INFO|STARTED [queue: \"default\", task: \"2a26f439-b2af-4ad0-8c43-09c7453c069f\", job: \"3ceed45c-e11c-4e9b-aa35-2d9cf9cee9c7\"]\n2024-04-18 08:30:59,161|INFO|Loading participants from Kronos\n2024-04-18 08:30:59,527|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:30:59,529|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:30:59,532|INFO|FAILURE [queue: \"default\", task: \"2a26f439-b2af-4ad0-8c43-09c7453c069f\", job: \"3ceed45c-e11c-4e9b-aa35-2d9cf9cee9c7\"]\n",
      "event": 12,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "34887895-a578-4633-8040-b228e5dcf3e4",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.471Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:01.667Z",
      "completed_on": "2024-04-18T08:31:01.958Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "3e18d175-cb06-4e93-8db8-e1c8562c1dc2",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:01,668|INFO|STARTED [queue: \"default\", task: \"34887895-a578-4633-8040-b228e5dcf3e4\", job: \"3e18d175-cb06-4e93-8db8-e1c8562c1dc2\"]\n2024-04-18 08:31:01,671|INFO|Loading participants from Kronos\n2024-04-18 08:31:01,957|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:01,957|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:01,958|INFO|FAILURE [queue: \"default\", task: \"34887895-a578-4633-8040-b228e5dcf3e4\", job: \"3e18d175-cb06-4e93-8db8-e1c8562c1dc2\"]\n",
      "event": 4,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "574e9b79-a0e9-4625-8c8b-abae25c54275",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.546Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:05.123Z",
      "completed_on": "2024-04-18T08:31:05.381Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "5b04b1ba-113a-4888-ab27-cdf61c56d842",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:05,124|INFO|STARTED [queue: \"default\", task: \"574e9b79-a0e9-4625-8c8b-abae25c54275\", job: \"5b04b1ba-113a-4888-ab27-cdf61c56d842\"]\n2024-04-18 08:31:05,126|INFO|Loading participants from Kronos\n2024-04-18 08:31:05,376|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:05,378|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:05,381|INFO|FAILURE [queue: \"default\", task: \"574e9b79-a0e9-4625-8c8b-abae25c54275\", job: \"5b04b1ba-113a-4888-ab27-cdf61c56d842\"]\n",
      "event": 17,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "5a68c03f-879b-42e2-883b-7e0addee16d9",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.433Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:00.010Z",
      "completed_on": "2024-04-18T08:31:00.350Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "3103a101-506a-4b6c-9dff-35716e2e70a9",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:00,011|INFO|STARTED [queue: \"default\", task: \"5a68c03f-879b-42e2-883b-7e0addee16d9\", job: \"3103a101-506a-4b6c-9dff-35716e2e70a9\"]\n2024-04-18 08:31:00,013|INFO|Loading participants from Kronos\n2024-04-18 08:31:00,346|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:00,348|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:00,351|INFO|FAILURE [queue: \"default\", task: \"5a68c03f-879b-42e2-883b-7e0addee16d9\", job: \"3103a101-506a-4b6c-9dff-35716e2e70a9\"]\n",
      "event": 9,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "89cc0bc2-307e-4422-a7a5-302a7cbc0e1d",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.485Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:02.363Z",
      "completed_on": "2024-04-18T08:31:02.691Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "cf29d4b1-c94c-4b97-bb61-51211fd003d5",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:02,363|INFO|STARTED [queue: \"default\", task: \"89cc0bc2-307e-4422-a7a5-302a7cbc0e1d\", job: \"cf29d4b1-c94c-4b97-bb61-51211fd003d5\"]\n2024-04-18 08:31:02,366|INFO|Loading participants from Kronos\n2024-04-18 08:31:02,687|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:02,689|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:02,691|INFO|FAILURE [queue: \"default\", task: \"89cc0bc2-307e-4422-a7a5-302a7cbc0e1d\", job: \"cf29d4b1-c94c-4b97-bb61-51211fd003d5\"]\n",
      "event": 8,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "8abfd666-3274-4543-954e-45d29201c1eb",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.366Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:30:56.426Z",
      "completed_on": "2024-04-18T08:30:57.070Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "14d4c9f5-efd1-4821-b5dd-a1f51da385f8",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:30:56,427|INFO|STARTED [queue: \"default\", task: \"8abfd666-3274-4543-954e-45d29201c1eb\", job: \"14d4c9f5-efd1-4821-b5dd-a1f51da385f8\"]\n2024-04-18 08:30:56,431|INFO|Loading participants from Kronos\n2024-04-18 08:30:57,069|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:30:57,069|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:30:57,071|INFO|FAILURE [queue: \"default\", task: \"8abfd666-3274-4543-954e-45d29201c1eb\", job: \"14d4c9f5-efd1-4821-b5dd-a1f51da385f8\"]\n",
      "event": 11,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "9f67ba9c-a8e1-4eda-9fff-128c4a9acfb8",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.463Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:01.279Z",
      "completed_on": "2024-04-18T08:31:01.579Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "92b2c994-49d3-4667-973e-225979104f5f",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:01,280|INFO|STARTED [queue: \"default\", task: \"9f67ba9c-a8e1-4eda-9fff-128c4a9acfb8\", job: \"92b2c994-49d3-4667-973e-225979104f5f\"]\n2024-04-18 08:31:01,285|INFO|Loading participants from Kronos\n2024-04-18 08:31:01,574|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:01,576|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:01,579|INFO|FAILURE [queue: \"default\", task: \"9f67ba9c-a8e1-4eda-9fff-128c4a9acfb8\", job: \"92b2c994-49d3-4667-973e-225979104f5f\"]\n",
      "event": 18,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "c91ead42-69f5-4aa9-93de-94e6b5ed43b6",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.520Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:04.096Z",
      "completed_on": "2024-04-18T08:31:04.358Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "5405b6aa-2b53-40b7-9716-26106e453cd5",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:04,097|INFO|STARTED [queue: \"default\", task: \"c91ead42-69f5-4aa9-93de-94e6b5ed43b6\", job: \"5405b6aa-2b53-40b7-9716-26106e453cd5\"]\n2024-04-18 08:31:04,100|INFO|Loading participants from Kronos\n2024-04-18 08:31:04,353|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:04,355|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:04,358|INFO|FAILURE [queue: \"default\", task: \"c91ead42-69f5-4aa9-93de-94e6b5ed43b6\", job: \"5405b6aa-2b53-40b7-9716-26106e453cd5\"]\n",
      "event": 20,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "dbcaa0d1-ce8e-40c0-8efb-e2a61ff6cb7d",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.425Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:30:59.617Z",
      "completed_on": "2024-04-18T08:30:59.939Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "1a142241-64ee-4802-b0df-47eb87132c11",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:30:59,618|INFO|STARTED [queue: \"default\", task: \"dbcaa0d1-ce8e-40c0-8efb-e2a61ff6cb7d\", job: \"1a142241-64ee-4802-b0df-47eb87132c11\"]\n2024-04-18 08:30:59,621|INFO|Loading participants from Kronos\n2024-04-18 08:30:59,935|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:30:59,937|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:30:59,939|INFO|FAILURE [queue: \"default\", task: \"dbcaa0d1-ce8e-40c0-8efb-e2a61ff6cb7d\", job: \"1a142241-64ee-4802-b0df-47eb87132c11\"]\n",
      "event": 15,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "de1f1084-e8b3-47a3-b3eb-61aeb7747641",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.528Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:04.435Z",
      "completed_on": "2024-04-18T08:31:04.730Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "d2aed8fe-f738-4e82-957e-01d8b6c97d65",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:04,436|INFO|STARTED [queue: \"default\", task: \"de1f1084-e8b3-47a3-b3eb-61aeb7747641\", job: \"d2aed8fe-f738-4e82-957e-01d8b6c97d65\"]\n2024-04-18 08:31:04,440|INFO|Loading participants from Kronos\n2024-04-18 08:31:04,726|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:04,728|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:04,730|INFO|FAILURE [queue: \"default\", task: \"de1f1084-e8b3-47a3-b3eb-61aeb7747641\", job: \"d2aed8fe-f738-4e82-957e-01d8b6c97d65\"]\n",
      "event": 14,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "debed060-54d2-4e57-b4b5-2389a9cda9fb",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.390Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:30:57.119Z",
      "completed_on": "2024-04-18T08:30:58.200Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "a73b4ec3-eae1-4474-b063-aa6ec5178fcc",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:30:57,119|INFO|STARTED [queue: \"default\", task: \"debed060-54d2-4e57-b4b5-2389a9cda9fb\", job: \"a73b4ec3-eae1-4474-b063-aa6ec5178fcc\"]\n2024-04-18 08:30:57,123|INFO|Loading participants from Kronos\n2024-04-18 08:30:58,195|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:30:58,197|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:30:58,200|INFO|FAILURE [queue: \"default\", task: \"debed060-54d2-4e57-b4b5-2389a9cda9fb\", job: \"a73b4ec3-eae1-4474-b063-aa6ec5178fcc\"]\n",
      "event": 10,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "f5ae3122-2ab6-44b8-8c8c-99d0b759a7c9",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.455Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:00.817Z",
      "completed_on": "2024-04-18T08:31:01.170Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "7fd5490c-a749-4ada-b2b7-bf1b2e063fdd",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:00,818|INFO|STARTED [queue: \"default\", task: \"f5ae3122-2ab6-44b8-8c8c-99d0b759a7c9\", job: \"7fd5490c-a749-4ada-b2b7-bf1b2e063fdd\"]\n2024-04-18 08:31:00,820|INFO|Loading participants from Kronos\n2024-04-18 08:31:01,165|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:01,167|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:01,170|INFO|FAILURE [queue: \"default\", task: \"f5ae3122-2ab6-44b8-8c8c-99d0b759a7c9\", job: \"7fd5490c-a749-4ada-b2b7-bf1b2e063fdd\"]\n",
      "event": 7,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  },
  {
    "model": "events.loadparticipantsfromkronostask",
    "pk": "fc30000e-e71e-4e30-bb33-0920f9ac237c",
    "fields": {
      "description": "",
      "created_on": "2024-04-18T08:30:56.505Z",
      "created_by": ["admin@example.com"],
      "started_on": "2024-04-18T08:31:03.467Z",
      "completed_on": "2024-04-18T08:31:03.723Z",
      "progress": null,
      "status": "FAILURE",
      "job_id": "f73fc216-f276-4c16-a655-ecbb85411b85",
      "mode": "ASYNC",
      "failure_reason": "403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token",
      "log_text": "2024-04-18 08:31:03,467|INFO|STARTED [queue: \"default\", task: \"fc30000e-e71e-4e30-bb33-0920f9ac237c\", job: \"f73fc216-f276-4c16-a655-ecbb85411b85\"]\n2024-04-18 08:31:03,470|INFO|Loading participants from Kronos\n2024-04-18 08:31:03,719|ERROR|403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n2024-04-18 08:31:03,721|ERROR|Traceback (most recent call last):\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/django_task/job.py\", line 51, in run\n    job_class.execute(job, task)\n  File \"/home/kiro/PycharmProjects/contactdb/events/jobs.py\", line 32, in execute\n    kronos_client.login()\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 35, in login\n    data = self._send_kronos(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/kiro/PycharmProjects/contactdb/events/kronos.py\", line 31, in _send_kronos\n    resp.raise_for_status()\n  File \"/home/kiro/PycharmProjects/contactdb/.venv/lib/python3.12/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://accounts.cbd.int/api/v2013/authentication/token\n\n2024-04-18 08:31:03,723|INFO|FAILURE [queue: \"default\", task: \"fc30000e-e71e-4e30-bb33-0920f9ac237c\", job: \"f73fc216-f276-4c16-a655-ecbb85411b85\"]\n",
      "event": 6,
      "contacts_nr": 0,
      "registrations_nr": 0,
      "conflicts_nr": 0,
      "skipped_nr": 0
    }
  }
]
